### ISSUE TITLE
Errors with grep and stall

### ISSUE THREAD

**Issue by Mek101** [mbideau/btrfs-diff-sh#1]
I tried to use this script on my void linux server, however it results in the following
```
[mek101@home-server ~]$ sudo ./Progetti/3party/btrfs-diff-sh/btrfs_diff.sh /mountpoints/private_storage/mek101/data_snapshot.20210103/ /mountpoints/private_storage/mek101/data_snapshot.20210221_15/
Password: 
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
```
Consulting `htop`, the scripts stalls at 17%~ cpu usage, and has to be terminated with `ctrl+c`
****
If it is of any help
```
[mek101@home-server ~]$ btrfs --version
btrfs-progs v5.9 
```

**Comment by mbideau** [comment]
Hi @Mek101,

Thank you very much for reporting the bugs.

It seems to be that case https://stackoverflow.com/a/26754351.

May be it misses an escaping of a grep expression which value contains a dash.

I need to dig deeper. But right now I have very little spare time to investigate.

Do you have any clue of which grep line it is ?

Can you run with the `DEBUG=btrfs-diff` mode and capture the output on _STDERR_ please ?

**Comment by Mek101** [comment]
Now, with `sudo DEBUG=btrfs-diff ./btrfs_diff.sh /mountpoints/private_storage/mek101/data_snapshot.20210207/ /mountpoints/private_storage/mek101/data_snapshot.20210307_8/`, it simply lists all the files with a [DEBUG] prefix and terminates with a sed error
```
[DEBUG]    ./data_snapshot.20210307_8/o171636-7918-0
[DEBUG]    /o171125-7290-0/Strumenti
[DEBUG]    ./data_snapshot.20210307_8/o171125-7290-0
[DEBUG]    /o171124-7290-0/Esercizi
[DEBUG]    ./data_snapshot.20210307_8/o171772-8048-0
[DEBUG]    /o171125-7290-0/ridirezionamentocircolare
[DEBUG]    ./data_snapshot.20210307_8/o167642-6102-0
[DEBUG]    /Documenti/Università/SistemiOperativi
[DEBUG]    ./data_snapshot.20210307_8/o171818-8209-0
[DEBUG]    /o167642-6102-0/Esercizi
[DEBUG]    ./data_snapshot.20210307_8/o171819-8209-0
[DEBUG]    /o171818-8209-0/es25_zombie
[DEBUG]    ---
[DEBUG]    removing line: '45:deleted: /o167647-6102-0/FINITE_QUEUE'
[DEBUG]    removing line: '46:deleted: /o167652-6102-0/1
[DEBUG] 48:deleted: /o167652-6102-0/2
[DEBUG] 50:deleted: /o167652-6102-0/EserciziRand
[DEBUG] 66:deleted: /o167652-6102-0/VECCHIESAMI
[DEBUG] 68:deleted: /o167652-6102-0/es1_tutto
[DEBUG] 70:deleted: /o167652-6102-0/es4_pthread_variabilecondivisa
[DEBUG] 72:deleted: /o167652-6102-0/es6_eliminaDaLista
[DEBUG] 74:deleted: /o167652-6102-0/es8PAR_consA+B'
sed: -e expression #1, char 3: unknown command: `
'
``` 

Also, I re-tried to let the command run again, and for some reason, the output changed
```
[mek101@home-server btrfs-diff-sh]$ sudo ./btrfs_diff.sh /mountpoints/private_storage/mek101/data_snapshot.20210207/ /mountpoints/private_storage/mek101/data_snapshot.20210307_9/ 
grep: Invalid range end
sed: -e expression #1, char 3: unknown command: `
'
```

**Comment by mbideau** [comment]
Thank you very much for your feedback.
My hypothesis is that you have some brackets [] in your file names, and since the code uses filenames in grep expression, it makes grep interpret the filename as a regex when it is not (at least the filename part).

Can you confirm/inform that by searching for brackets in your file names ?

I should definitively add some escaping to those parts, but I can't do it this week. May be next weekend.

May be it is the same for the _sed_ expression. I would double check all use of filenames in regex.

Thank you again

**Comment by Mek101** [comment]
Yup I do. A folder and 9 songs

**Comment by mbideau** [comment]
Hey @Mek101,

I am very sorry for the huge time I took to fix this :pray: 
I really didn't had enough personal free time those last months.

Anyway, can you try again on your setup and tell me how it goes ?
I have added a test case with a single filename but with a totally ugly name (i.e.: full of non-alphanum chars) and it passes perfectly.

Hope you are still here ?  :relaxed:

Thank you in advance for your feedback.

**Comment by Mek101** [comment]
I got to test it out only now: it's not exactly fast with 200+ GB subvolumes but it works 😄

**Comment by mbideau** [comment]
@Mek101 Cool :ok_hand: 
Can you give me any number about the **duration**, the **fs options**, and your **disk info** ? Just to get an idea. That would be awesome.
As soon as I have more spare free time, I'll try to make it work with the _go_ version.

**Comment by Mek101** [comment]
"disk info"?

**Comment by Mek101** [comment]
"disk info"?

**Comment by mbideau** [comment]
@Mek101 Hi again,

Yes, "disk info" is to know what kind of hardware you are running your test on. It is not very important, but it is just an extra piece of information that allows to better appreciate the result.

If you are willing to, I suggest you also test with the updated GO binary (you'll have to compile it, but it is really simple, check the comments at the top of the source code), see https://github.com/mbideau/btrfs-diff-go
If you need any help, please tell me.
The command will probably crash because of the _clone_ instruction, in that case could you please run it again with the option `--debug` and send me the output payload as an attachment, it would help me to debug (I cannot re-create that bug myself, since I do not really know what that instruction is used for).

Thank you very much for your feedback, very appreciated :pray:

**Comment by mbideau** [comment]
@Mek101 Hi,
I just wanted to let you know that I have fixed the [Go version](https://github.com/mbideau/btrfs-diff-go) of this program.
Would you agree to benchmark it against the Shell version, in term of time to process ? It would be awesome ! :pray:  :sweat_smile: 
If you do so, please open a new issue :wink: 
Keep me posted...

Thank you again.
Have a nice day.

**Comment by Mek101** [comment]
> @Mek101 Hi again,
> 
> Yes, "disk info" is to know what kind of hardware you are running your test on. It is not very important, but it is just an extra piece of information that allows to better appreciate the result.
> 
> If you are willing to, I suggest you also test with the updated GO binary (you'll have to compile it, but it is really simple, check the comments at the top of the source code), see https://github.com/mbideau/btrfs-diff-go
> If you need any help, please tell me.
> The command will probably crash because of the _clone_ instruction, in that case could you please run it again with the option `--debug` and send me the output payload as an attachment, it would help me to debug (I cannot re-create that bug myself, since I do not really know what that instruction is used for).
> 
> Thank you very much for your feedback, very appreciated 🙏

Took me a while since I was finalizing my OS disk migration since the original broke down.
Anyway: the volume is a RAID 1 with 2 `HITACHI HUA723020ALA640` mounted with `defaults,nofail,nossd,compress-force=zstd,space_cache`.
Subvolume size and bench incoming, since they're quite huge

**Comment by Mek101** [comment]
`# time btrfs-diff /mountpoints/raid1/anime/data_snapshot.20210816/ /mountpoints/raid1/anime/bk_data_snapshot.2021094/`
got me
```
real	19m25,087s
user	20m23,584s
sys	7m35,970s
```
with them being
```
495G	data_snapshot.20210816/
535G	bk_data_snapshot.20210904
```

Also there was some padding on "Added" statements for some reason...?
```
...
  added: /Tensei Shitara Slime Datta Ken/Stagione 2/Part 1
  added: /Tensei Shitara Slime Datta Ken/Stagione 2/Part 2
changed: /Higurashi No Naku Koro Ni/Higurashi No Naku Koro Ni (3° serie) Rei/[DN Team] Higurashi no Naku Koro ni Rei OAV 1-5 END [720p][H264_AAC][Sub Ita]/[DN Team] Higurashi no Naku Koro ni Rei - 01 [720p][H264_AAC][Sub Ita][5335E623].mp4.part
changed: /Higurashi No Naku Koro Ni/Higurashi No Naku Koro Ni (3° serie) Rei/[DN Team] Higurashi no Naku Koro ni Rei OAV 1-5 END [720p][H264_AAC][Sub Ita]/[DN Team] Higurashi no Naku Koro ni Rei - 03 [720p][H264_AAC][Sub Ita][43E84833].mp4.part
...
```

**Comment by Mek101** [comment]
Performance comparison:
https://github.com/mbideau/btrfs-diff-go/issues/2

**Comment by mbideau** [comment]
Hi @Mek101,
Thank you very much for all that feedback.
It is very appreciated ! :pray: 
I will dig into that today.
I keep you posted.

**Comment by mbideau** [comment]
I am closing that issue, since it has been resolved.
I will continue in the one you created.
I also have created a new one for _Poor performances report_, like you see above.
